ARM-DOE/ACT

- act/plotting/plot.py
Not having this line created odd behavior where one blank plot would be made in addition to the plot that was needed when display.add_subplots() was called.
> FIX: Now close plot before creating a new one in add_subplots

- README.rst
- examples/multidata_example.py
The file name in the multi-dataset plotting example is now more descriptive.
> DOC: Better file name in example.

- act/io/armfiles.py
- act/io/csvfiles.py
This addresses #36 and eliminates the warning message when a dataset doesn't conform to ARM standards as well as allows keyword arguments for pd.read_csv and xr.open_mfdataset for the read functions.
> ADD: kwargs to read functions, eliminate annoying warning

- docs/source/installation.rst
We now explictly state that Python 3.6 or greater is needed to run ACT. This takes care of #23.
> ADD: Minimum python version to docs.

- act/io/__init__.py
- act/io/csvfiles.py
- docs/source/API/Clean.rst
- docs/source/API/io.rst
There was an issue in the documentation where you could not read the documentation for the act.io.csvfiles and act.io.clean methods. Now that has been fixed.
> DOC: Now we can actually get to csvfiles and clean in the docs.

- CONTRIBUTING.rst
- docs/source/CONTRIBUTING.rst
- docs/source/index.rst
@rcjackson Question, so the doc for contributors guide fails due to the python code blocks trying to import the actually library but I figured I save a space for the pull request, but is there a way to display python code in the rst file without using the actually act code?
> DOC: Updating contributor's guide.  More info on doc strings, PEP8, git branches and more.

- act/io/clean.py
- act/tests/test_clean.py
This is an update to help fix issues with xarray converting any variable with _FillValue or missing_value attribute set.  If xarray finds a variable like this it will convert the variable to float and change any missing value indicator to nan. This is fine for data but not good for qc or state fields.
I also updated some of the other functions as there were some minor issues and duplication.
> Clean state

- act/io/armfiles.py
The DQ office was having issues reading multiple radar files, removing the parallel argument solved this issue. We believe that removing the keyword and having the option to pass in parallel=True explicitly is a better option. I also removed the variables keyword since it was not being used, and moved the concat_dim keyword into the function call.
> changing arguments in reader

- act/corrections/__init__.py
- act/corrections/ceil.py
- act/corrections/mpl.py
- act/discovery/__init__.py
- act/discovery/get_armfiles.py
- act/io/armfiles.py
- act/io/clean.py
- act/io/csvfiles.py
- act/io/dataset.py
- act/plotting/GeoDisplay.py
- act/plotting/SkewTDisplay.py
- act/plotting/TimeSeriesDisplay.py
- act/plotting/WindRoseDisplay.py
- act/plotting/XSectionDisplay.py
- act/plotting/common.py
- act/plotting/plot.py
- act/retrievals/stability_indices.py
- act/tests/test_utils.py
- act/utils/__init__.py
- act/utils/data_utils.py
- act/utils/datetime_utils.py
- docs/source/API/generated/act.corrections.ceil.correct_ceil.rst
- docs/source/API/generated/act.plotting.common.get_date_format.rst
- docs/source/API/generated/act.plotting.common.parse_ax.rst
- docs/source/API/generated/act.plotting.common.parse_ax_fig.rst
- docs/source/API/generated/act.utils.data_utils.add_in_nan.rst
- docs/source/API/generated/act.utils.datetime_utils.dates_between.rst
To be more consistent between submodules and code, added colon between parameter definitions in docs. Fixed a few spelling errors and added space at the end of doc strings to be more in line with nump standards. I also changed the import of the utils to remove the need for a longer extension. IO import are the same to keep different datatype modules separate.
> STY: Multiple style changes, mispelling, imports and more.

- act/io/armfiles.py
Older ARM files do not have a `time` variable. Only `base_time` and `time_offset` exist in the file. Need to use `time_offset` variable. This will rename the `time_offset` variable to `time` and set as the time coordinate.
> Use time_offset when time not in file

- act/plotting/TimeSeriesDisplay.py
When the day night background is used in plotting (specifically at high latitude sites such as NSA), astral will throw an error when the sun doesn't set in the summer months. I made a small update that will make the plot continuously day-colored if the sun doesn't set below the six degree horizon threshold set by astral.
> adding day night background for 24 hour sunlight

- act/io/clean.py
- act/qc/qcfilter.py
Adam pointed out that if the user reads in regular ARM data with embedded QC fields and does not run clean.cleanup() method on the object, the qcfilter methods will not work correctly. I've added a check into any of the qcfilter methods to run clean.cleanup() to ensure things work smoothly. I also updated clean.cleanup() to fix an issue with not translating bits higher than 9 and adding bit_#_comment attributes.
> qcfilter update

- act/io/clean.py
- act/plotting/TimeSeriesDisplay.py
The exception to catch errors when plotting at high latitude and no sunset is not working correctly. I've updated the exception to use plot range instead of trying to get time range from object. Also, updated the exception to be more specific.
Added exception to catch errors when location variables are not in the object. It will do a smart search for known variable names first, then look for standard_name then return gracefully.
Also, minor issue with cleanup and checking long_name.
> High lat background for plots

- act/io/clean.py
Fixing issue with "(" and ")"  in re after switching to new method for detecting QC variables.
I ran the pytest -v locally and there is a failure in something I didn't touch. Not sure if this will have a failure or not.
> Fixing issue I introduced with recent update detecting QC variables.

- act/plotting/act_cmap.py
After the color map update a new warning was displayed indicating issue looking for 'red' in a non-dictionary object. I'm adding an if statement to make the warnings go away.
> Fixing warning caused by looking for a color "red" in a non-dict object.

- act/retrievals/__init__.py
- act/retrievals/pwv_calc.py
- act/tests/test_retrievals.py
For some of our DQ Office plots, we have been calculating precipitable water vapor values from sonde data, notably to compare with other instruments that measure pwv directly (see image). This was done in our IDL code as well, but I re-wrote it in python with more up-to-date equations. I think that this would be useful to have in ACT for anyone who is using ARM sonde data.
> adding precipitable water calculation for sonde data

- act/utils/data_utils.py
When there is only one time step add_in_nan has a problem with the mode stats.
> Fixing issue with add_in_nan when there is only one time step.

- act/plotting/TimeSeriesDisplay.py
I'm getting an error while plotting data not read in with the ACT reader. This try will allow data to be plotted with an Xarray Dataset read with Xarray only reader. I think this is the last bit of removing the act object variables.
> Adding a Try to catch when file_dates not set in object.

- docs/source/installation.rst
I found an outdated statement in the documentation saying that we soon "plan on implementing pip and conda install" when we did that ages ago. I have removed the statement from the docs.
> DOC: Removing odd statement in the installation section.

- act/io/armfiles.py
- act/io/clean.py
Also updated the error handling for FileNotFoundError.
This all came about after we updated combine='by_coords'. I still think this is the correct method but we discovered that the way Xarray reads the units string with time is not correct. It does not handle the timezone offset part at the end of the units string. This was causing it to not set the time correctly, but date was correct. To fix this we are setting use_cftime=True to force it to use the cftime library to fix the units string reading part. The issue is that this will read the data in as cftime and leave it that way in the returned object. The second part of this is to convert the time back to expected numpy datetime64 values.
I also updated the way we handle the errors so we can fine tune the error handling and use the error …
> A few changes to fix how xarray reads the time units string. 

- act/utils/ship_utils.py
- docs/source/CONTRIBUTING.rst
- docs/source/CREATING_ENVIRONMENTS.rst
- docs/source/installation.rst
- docs/source/release-history.rst
Making required changes in the documentation to account for the change in the ACT repo's ownership. The largest change is that the new website is now at https://ARM-DOE.github.io/ACT.
I also updated the release history to be current.
> DOC: Changes to docs to account for switching of repo ownership.

- act/plotting/TimeSeriesDisplay.py
There is a problem when plotting data that have lat/lon as vectors when making the day night background. Just changed the method for getting data from .data to .values to return numpy array instead of dask object.
> Fixing issue when plotting data with lat and lon as vectors with day_ight_background set.

- act/plotting/TimeSeriesDisplay.py
In certain datastreams, the height dimension is set to an integer-based index (ie, number of vertical levels of data rather than height in km) with height as a separate variable not used as a dimension. Using TimeSeriesDisplay.plot would result in the following:
I added an option to the plotting methods that don't explicitly set the y-axis to allow for a user to set height as the y variable provided the passed variable has the same shape. If it does not then it will default back to the original. 
I also added the option of setting the colorbar label manually. This already existed in time_height_scatter so I added it to the other plotting methods that called Display.add_colorbar. Here is an updated plot using these changes:
> ADD: Options to customize ydata and colorbar labels

- act/plotting/HistogramDisplay.py
Removed plot_quartiles from plot_stairstep_graph and plot_heatmap since it was not being used anywhere in the code.
It was listed as a variable in the definitions but not listed in the parameters or used anywhere in the code.
> MNT: removed plot_quartiles since it was not being used

- act/discovery/get_armfiles.py
When a user placed improper login information to the ARM Data Discovery download tool it would display an error message and then exit the python program. However, it would fail at doing so because sys.exit was not imported correctly. I've changed this to have a more proper behavior where an exception is raised rather than exiting the entire program.
> FIX: Handling of improper user name in data discovery download tool.

- act/plotting/TimeSeriesDisplay.py
In instances where the number of x or y data points is less than half of the given num_barbs_x/num_barbs_y number, the barb_step_x/barb_step_y value will round down to zero and a ValueError will be raised when attempting to plot. Adding slice step floor value of 1 to mitigate this.
> FIX: Adding floor to barb step to avoid zero value

- act/qc/clean.py
Initially I tried to not use the qc_ at start of quality control variables since that is only an ARM standard, and ARM does not follow its own standards. But there is no reasonable way to code up all the minor differences with the attributes of ARM QC variables, so I'm adding in some code to also look for qc_ in the variable name.
> Fixing issue getting quality control variable names

- act/corrections/mpl.py
Adding correction if height dimension is 2D instead of expected 1D. This happens when xarray combines multiple files and the coordinate dimension changes values or shape between files. This is causing issues to subset height to positive values only.
> Fixing 2D heights

- act/plotting/SkewTDisplay.py
- act/retrievals/stability_indices.py
This addresses #194, where I add in a few more exceptions in case there is an improper MetPy installation.
> ENH: Improved detection of properly installed MetPy

- act/retrievals/irt.py
Noticed that the function fails on nan ir temperatures.  Fix for that
> ENH: Adding catch for nan data

- act/qc/clean.py
- act/qc/comparison_tests.py
- act/qc/qcfilter.py
- act/qc/qctests.py
In get_qc_test_mask() the returned value is expected to be a numpy masked array. Turns out the default behavior of numpy ma is to not make a ma if all mask values are to be set to False. This is not what we want. Need to set a keyword to force creation of ma even when all mask values are False.
Also updated the returned tuple from setting tests to have the data variable name as one of the members of the tuple. While in there fixed some documentation.
> Fixing issue with making numpy mask

- .travis.yml
- README.rst
- act/plotting/SkewTDisplay.py
- act/retrievals/stability_indices.py
- act/tests/test_plotting.py
- act/tests/test_retrievals.py
- continuous_integration/environment-3.6.yml
- continuous_integration/environment-3.7.yml
- continuous_integration/install.sh
- examples/plot_skewt.py
- requirements.txt
While working on the updates for coveralls incorporation for code coverage, I ran into the same errors @kenkehoe did with cartopy and metpy.  While we say METPy is an optional dependency, our tests, examples, and some code assumed it was available.  This should be updated.
There was an issue with the GeoDisplay plotting causing core dumps during the testing.  I commented this out for now as there was no indication on what could be causing the issue.  No errors came up in testing on my local system.
> Coveralls Integration and Workarounds for Cartopy and METPy

- environment.yml
Conda has issues with astral that I am trying to work around.
> ENH: Moving astral to pip install for conda

- act/qc/radiometer_tests.py
There is a warning about values in the fftv variable: " RuntimeWarning: invalid value encountered in less idx = (fftv < 1.)". Just adding a warning capture in a with: to suppress the output.
> Capturing warning about NaNs with comparisons.

- act/qc/radiometer_tests.py
Adds the FFT and frequency data to the object so that users can plot up the data like so:
`  
nrows = 6 
ncols = 4
x = 0
y = 0
fig, ax = plt.subplots(nrows, ncols, figsize=(15,10))
sdate = pd.to_datetime(obj['time'].values[0])
upper = obj['fft'].attrs['upper_freq']
lower = obj['fft'].attrs['lower_freq']
#Plots data up in hourly increments
for i in range(24):
dummy = obj.sel({'time': slice(sdate.replace(hour=i, minute=0, second=0),
sdate.replace(hour=i, minute=0, second=0) +
pd.Timedelta(1,'hours'))})
ax[x,y].set_xlim([np.nanmin(obj['fft_freq']), np.nanmax(obj['fft_freq'])])
ax[x, y].axvspan(lower[0], upper[0], color='red', alpha=0.25)
ax[x, y].axvspan(lower[1], upper[1], color='red', alpha=0.25)
ax[x, y].set_title(str(i).zfill(2) + '00')
if len(dummy['time'].values) > 1:
ax[x, …
> ENH: Updates to the FFT radiometer test to allow users to plot up FFT

- act/plotting/TimeSeriesDisplay.py
While applying the abs_limits to a plot discovered a limit value of 0 is interpreted incorrectly as None/False so it is not bing used. Updated the code to correctly look for a value of None directly so a value of 0 can be used.
> Fixing issue when abs_limits set to a value of zero is interpreted wrong for applying values

- act/discovery/get_armfiles.py
I've added the ability to specify a specific time when using the ACT discovery download tool. If you set the date to None, it will download all times on the given day, just as it worked before. 
I don't think we ever got to unit testing this, simply because we have to find a way to encrypt the token for the test.
> ADD: Ability to specify specific time for data download.

- environment.yml
Added cartopy as a package to be downloaded when creating an environment using the environment.yml file. It's listed as a required dependency but was missing from the .yml file.
> UPDATE: Added cartopy to environment download

- act/tests/test_utils.py
- act/utils/geo_utils.py
The way these values are calculated it needs to find an instance. At high latitudes it needs to look a larger number of days forward and backward to find an instance when there are polar night/day. Increasing number of days to calculate to find matches.
> Fixing issue calculating solar noon, sunrise, sunset at high latitude.

- act/plotting/timeseriesdisplay.py
- act/qc/qcfilter.py
Numpy has updated the way to set data type and there is currently a warning for one last place we use the old format. This fixes that warning. Also, fixing issue setting yrange on plots when there are inf values.
> Numpy float 

- act/qc/qcfilter.py
This fixes #347 by using `coords` instead of `dims` in the construction of a new `DataArray` added to `self._obj`.
> Use coords when adding new DataArray

- act/utils/data_utils.py
np.unique was marking 2 sweeps even though there was 1, which was doubling nrays. Also added brackets for lat, lon, alt, as these need to be singular arrays for Py-ART. Also pep8 style fixes etc.
> FIX: Fixes for the pyart_obj creation.

- .travis.yml
- act/tests/test_plotting.py
- continuous_integration/environment-3.7.yml
- continuous_integration/environment-3.8.yml
- requirements.txt
Matplotlib 3.5.0 breaks the sonde plotting so ensuring 3.4.3 or less is used for matplotlib
> ENH: Updating requires to not include matplotlib 3.5.0

- act/qc/clean.py
Catching cases when flag_values or flag_masks are incorrectly set as strings. Sometimes we have incorrectly formatted files. This update will catch and fix those instances. Such is the life in ARM.
> Fix flag_values set as a single string

- act/qc/clean.py
The cleanup QC method has a logic error where it returns inside a loop when it should continue. Additional variables are not being processed.
> Fixing logic from a return to a continue

- act/qc/clean.py
- act/qc/qcfilter.py
- act/tests/test_qc.py
Issue #391 pointed out a performance issue with setting a new QC test. Turns out there was a call to .clean.cleanup() in the add_test() method via check_for_ancillary_qc() that was unnecessary and causing a significant number of loops to be executed. The default has been changed so clean.cleanup() is not run. Also, updated the way the QC variable names are extracted from the object to be more efficient and more accurate.
To ensure this type of thing does not happen again with a change to the QC code, I've added a test of the performance of the add_test() method. It uses wall clock time so it's not the best methodology, but should highlight significant performance decreases.
Overall this is a significant performance boost with a 60 fold decrease in computation time.
> QC processing time

- docs/source/conf.py
Add a Google Analytics ID to the `conf.py` file used by sphinx. For those interested in having access the analytics, you will need to send over your gmail address
Fixes #396
> Add Google Analytics ID

- docs/source/conf.py
Looks like I spoke too soon - within the read the docs theme, [they mention how to add the ID](https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html?highlight=analytics#confval-analytics_id), which is different from the PyData theme I used before... the main change being `analytics_id` instead of `google_analytics_id`
> Fix Google Analytics to Match RTD Theme

- act/io/armfiles.py
Turns out there was an unnecessary check on filename list length that was assuming filename was a list. This resulted in excluding single value lists from setting the kwargs values. We need to set these to ensure using use_cftime keyword is used.
> Not setting keywords for open_mfdataset() call

- .github/workflows/build-docs.yml
- .github/workflows/python-package-conda.yml
Ensure that the doc/ci workflows utilize the `main` branch instead of `master`
> Rename Master to Main

- .github/workflows/python-package-conda.yml
- README.rst
Pytest and flake8 requirements were updated with the switch to github actions which is causing us to miss a few things I think on PRs.  Trying to bring back to original standards.
> ADD: Adding coveralls back in, updating pytest and flake8 as well

- docs/environment_docs.yml
For the environment docs, make sure to use MetPy version >=1.2
> Pin MetPy version

- continuous_integration/environment_actions.yml
- requirements.txt
> CI: Pinning numpy as binarys between releases are having issues etc.

- act/qc/qcfilter.py
- act/tests/test_qc.py
Noticed this method was not storing the data back in the Dataset in the same format as was retrieved. This will check if data is set as Dask array and set data to same data type. Also, added some more tests.
> Updated to set data as Dask array back in Dataset if data is originally stored as Dask array

- act/qc/qcfilter.py
Turns out the code was defaulting to set the data back into the Dataset
as a numpy masked array. I think this was done to preserve integer
data type. But when setting the data back as a Dask array this does
not work correctly. Also, not sure the xarray methods would work
correctly anyway so changed to set as Dask array with NaN values
or Numpy array with NaN values. Also added a check to ensure the
needed keywords are set.
> Fixing issue setting data to Dask array in datafilter

- act/config.py
- act/io/armfiles.py
- act/qc/arm.py
- act/tests/test_io.py
The reader allows the use of drop_variables to not read in variables
but this requires the knowledge of the variable names to drop. This
feature allows for setting the variables to keep and it will figure the
names of the variables to add to drop_variables to not read in.
Part of #431
> Adding keep_variables to reader

- act/utils/datetime_utils.py
For the ARMLive API, we are missing colons in between hour, minute, and second
> FIX: Fix hour minute second format for ARMLive

- act/discovery/get_armfiles.py
- act/tests/test_utils.py
Fix the failing CI caused by a missing % sign in the strftime call in the ARMLive url building
> FIX: Fix failing ci by adding missing % to ARMLive

- act/discovery/get_armfiles.py
Currently, we add a single day when start date == end date for the ARM data discovery. This uses a delta of 23 hours, 59 minutes, and 59 seconds, which will restrict the search to a single day.
> FIX: Add barely less than a day for same time

- .github/workflows/python-package-conda.yml
Upgrade the versions we support, and remove Python 3.6 tests
> ENH: Remove Python 3.6 tests, add 3.10 tests

- act/io/icartt.py
This will resolve #529. The issue was that there was a 'qc_flag' variable with no corresponding 'flag' variable which goes against the standards expected.  I updated the qc_flag variable in the icartt read function to 'quality_flag' which appears to. solve things.
> ENH: Fixes an issue with cleaning up the qc for icartt.

- act/plotting/timeseriesdisplay.py
- act/tests/test_plotting.py
Previously we could set the plot() method keyword time_xrng with a list of datetime.datetime values. PR #534 changed the logic to not allow datetime.datetime values. This PR adds a check to convert values just like the Pandas check. This PR resolves issue #557 .
> Setting time_xrng with datetime values

- act/tests/test_plotting.py
- act/tests/test_retrievals.py
Tests failed with metpy not installed, which shouldn't be the case, fixing functions to follow pytest skipif
> TST: Updating test suite for pytest skip if for metpy.

- docs/environment_docs.yml
- docs/source/conf.py
Was a duplicate sphinx install as well.
> MNT: Removes language warning.

- .github/workflows/python-package-conda.yml
- README.rst
- act/plotting/skewtdisplay.py
- act/qc/qctests.py
- act/retrievals/sonde.py
- act/tests/test_plotting.py
- act/tests/test_qc.py
- act/tests/test_retrievals.py
- act/utils/data_utils.py
- continuous_integration/environment_actions.yml
- docs/source/index.rst
- docs/source/userguide/installation.rst
- environment.yml
- examples/plot_skewt.py
- requirements.txt
lxml is needed despite not existing in the ACT codebase itself but used by pandas. And fixing tests that weren't optional.
> FIX: lxml was needed and scikit and metpy qc tests weren't optional.

- act/__init__.py
- setup.py
My understanding of namespace packing was incorrect, so the submodule finding using namespace was conflicting with existing __init__.py files causing issues for installation. This should fix the feedstock testing. WIll need to look into more on why namespace warnings exist.
> FIX: Fixes install issues for conda-forge. Namespace was being used incorrectly.

- requirements.txt
adds metpy and removes duplicate lazy_loader closes #586
> FIX: Add metpy to requirements.txt.

- act/retrievals/sonde.py
- act/tests/test_retrievals.py
This includes a second method (Heffter) for calculating PBL from radiosonde data.  I've compared with months of ARM VAP data and there are some slight differences due to different methods for gridding.  There are also some larger differences which upon investigation look like potential problems with the VAP.  These have been reported and are being looked at.  Currently there is a mean difference of -27m.
This method follows Heffter's criteria for finding PBL height with the same smoothing/gridding as was being performed in the Liu Liang method.  To this end, the overlapping preprocessing of the radiosonde data has been separated out into an individual function to simplify the codes.  This did cause some differences in the Liu Liang method, specifically the removal of the altitude …
> ADD: New function for calculating PBL using the Heffter method

- act/retrievals/doppler_lidar.py
There is an issue when processing DL PPI to derive winds when the winds are not calculated. The returned values are np.nan values instead of xarray Dataset. Merging np.nan using xarray causes an error. This update checks data type and only attempts to merge Datasets.
> Correctly handling PPI derived winds when the function returns all NaNs

- act/plotting/timeseriesdisplay.py
There is an error in my previous PR for fixing the xlim when the values are set to the same value. This is a bug fix for correctly detecting how to make the fix.
> Fixing method of determining if value is numpy in xlim set to same value warning.

- act/tests/test_utils.py
- act/utils/data_utils.py
- act/utils/datetime_utils.py
There is a warning from stats.mode() indicating that the need to indicate if a single value dimension should be dropped from the returned values. This PR explicitly sets the keyword to remove the warning and return a scalar when we desire a scalar.
Needed to add a try/except for the numpy 1.10 to 1.11 transition period. The keyword only exists in Numpy 1.11 and newer so for backward compatibility need to catch the error and use previous syntax.
> Updated to new required keyword in stats.mode(). 

- act/plotting/histogramdisplay.py
- act/tests/test_plotting.py
- examples/plotting/plot_hist_kwargs.py
> MNT: Missing kwargs from axes.step.

- act/tests/test_retrievals.py
- continuous_integration/environment_actions.yml
- examples/plotting/plot_sonde.py
- requirements.txt
> MNT: Change naming to MET as its plotting met data.

- act/tests/test_discovery.py
Fix failing CI due to airnow test suite
> Fix Airnow Test

- act/plotting/geodisplay.py
- act/plotting/timeseriesdisplay.py
- act/plotting/windrosedisplay.py
This is to avoid the code breaking in a future matplotlib update.
> FIX: Warnings for matplotlib new syntax. Has been fixed with new call.

- .gitignore
- CONTRIBUTING.rst
> MNT: Update .gitignore to be more robust with downloaded test files.

- act/io/csvfiles.py
Ensure units are set properly for datetime in csv reader
> Make sure to set units on datetime

- examples/plotting/plot_violin.py
the Violin Plotting example is currently not generating on the website due to repeating title information
> BUG: Fixing title of violin example plot

- act/corrections/mpl.py
- act/discovery/__init__.py
- act/discovery/get_arm.py
- act/io/armfiles.py
- act/plotting/__init__.py
- act/plotting/windrosedisplay.py
- act/qc/qcfilter.py
- act/tests/test_correct.py
- codecov.yml
> Random updates

- act/plotting/skewtdisplay.py
- act/plotting/timeseriesdisplay.py
Updated skew-t plots to make it a little more robust and handle cases where data are subsetted from a 2D array.
> ENH: Updates for plotting

- act/tests/test_utils.py
- act/utils/data_utils.py
- examples/utils/plot_parse_filename.py
> Adding filename parsing for ARM filenames.

- act/qc/qcfilter.py
- act/tests/test_qc.py
This PR fixes an issue where calling `ds.qcfilter.add_test(...)` with `index=np.array([False])` or `index=np.array([True])` would set the bit to the opposite of what it should be.
> Fix `qcfilter.add_test` index

- requirements.txt
This PR removes the `pandas<2.0` restriction in `requirements.txt`. Tests passing locally, no other changes needed.
> Allow pandas v2

- act/tests/test_plotting.py
- continuous_integration/environment_actions.yml
Had to reopen PR as PR wasn't updating to new commits (First for everything). Also add timeout for get_ord stalling
> CI: Pandas remove

- act/io/armfiles.py
- act/io/noaagml.py
- act/io/noaapsl.py
- act/io/sodar.py
Fixes to remove warnings in IO. All warnings left in IO are either dependency warnings outside our control or are 2.0 deprecation warnings.
> FIX: IO Warning fixes.

- .github/workflows/python-package-conda.yml
Fix the python version spec in setting up the micromamba env
> FIX: Use the new syntax for setup micromamba

- act/qc/arm.py
- act/tests/test_qc.py
This update will use the new ARM DQR web-service for applying DQRs. I updated to testing to ensure the keywords are used correctly.
- [ X] Closes #733
> Updated DQR tool to use new DQR web-service.

- act/qc/bsrn_tests.py
- act/qc/clean.py
- act/tests/test_plotting.py
- act/utils/data_utils.py
The Pint library is warning of redefining units. This update correctly adds the desired units and stops redefining units. Also commented out some return statements in plotting testing to stop warnings of future errors.
> Pint update to stop warning

- act/plotting/timeseriesdisplay.py
Resolving issue when checking if data is finite when the data object type is not a Numpy array. This will try to extract the numpy array from the DataArray. Wrapped in a try to catch when the data is already a numpy array or is something else.
> converting data to numpy array before checking data with numpy function

- act/plotting/geodisplay.py
- act/tests/test_plotting.py
> MNT: Remove stamen for v2.0.

- act/tests/test_utils.py
- act/utils/data_utils.py
There is an issue with plotting multiple data files with a large data gap and 2D data. Inserting on NaN value allows the plot to streak the image. This PR will insert 2 NaN values to stop the streaking.
- [ X] Closes #766 
> Correctly inserting two nan values for 2D plots to ensure minimal streaking in plot.

- README.rst
- act/tests/utils/test_io_utils.py
- act/utils/__init__.py
- act/utils/io_utils.py
- continuous_integration/environment_actions.yml
- docs/environment_docs.yml
> Base functionality to create movies from images

- act/tests/utils/test_io_utils.py
- act/utils/io_utils.py
Updated generate_movie() to add functionality by allowing more flexibility with images parameter. Also adding ability to convert movie type (to some degree).
> Adding functionality to generate_movie().

- act/qc/radiometer_tests.py
There is a chance that the division could cause error when the mean is zero. This just catches that instance and handles correctly.
- [ X ] PEP8 Standards or use of linter
> Catching divide by 0 error before it errors.

- act/io/__init__.py
- act/io/hysplit.py
- act/tests/sample_files.py
- examples/io/plot_hysplit.py
- tests/io/test_hysplit.py
Hello. I have added a HYSPLIT trajectory reader in the ACT io module along with an example of how to use GeographicPlotDisplay to plot the trajectory.
> ADD: Hysplit reader in io module

- act/io/hysplit.py
- act/utils/data_utils.py
- examples/plotting/plot_scatter.py
- tests/utils/test_data_utils.py
This adds keywords to the convert_units method to notify user when the conversion fail. Because of how the method can loop through all the variables in the Dataset we don't want to print or raise exceptions when a conversion fails. This adds options the user can implement. I tried to use warnings but they didn't work so it's a print statement.
- [ X] Closes #793
- [X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming
> Unit conversion warning

- .github/workflows/ci.yml
Update codecov to user version 4 to avoid node 16 depreciation warning. Newer version of codecov uses secrets.
> CI: Update codecov.yml.

- act/io/arm.py
Trying to understand the encoding was a learning experience to say the least. The input encoding is 'float64' so I set it to that. 'datetime64[ns]' does not work.
> FIX: Fix for new xarray check for dtype.

- act/discovery/airnow.py
- act/plotting/timeseriesdisplay.py
> Airnow bug

- act/qc/comparison_tests.py
- act/utils/data_utils.py
- act/utils/datetime_utils.py
- tests/utils/test_data_utils.py
Updating DatastreamParserACT to accept pathlib.PosixPath as well as string paths. Fixing a few datetime64 calls to remove warnings during testing.
> Update DatastreamParser to accecpt pathlib.PosixPath

- act/retrievals/doppler_lidar.py
The VAD code would not work if only signal_to_noise_ratio was defined and intensity was set to None due to an undefined variable name. This remedies this by pointing the var_name to be the snr_name which is only used to get the height_name.
> FIX: Small error in Doppler lidar code with undefined var_name

- act/tests/__init__.py
- act/tests/sample_files.py
- act/utils/__init__.py
- act/utils/data_utils.py
- act/utils/io_utils.py
- continuous_integration/environment_actions.yml
- docs/environment_docs.yml
- examples/utils/plot_calculated_percentages.py
- tests/utils/test_data_utils.py
- tests/utils/test_io_utils.py
This function allows the user (ex: aerosol data) to provide fields and calculate the percentage of that field in a volume. The code also checks for invalid numbers if the user provides a threshold. User can also provided a specific time, a range of times, or get an mean of the whole dataset.
This function will eventually be used for the PieChart function I'm working on.
> ADD: calculate_percentage function.

- act/utils/inst_utils.py
After discussion with Matt, there seems to be another error code present in the present weather code set called 'ER' this change will check for that as well as changes in dtype for the weather codes, such as string '00' instead of expected int 0
> ENH: Check for ER codes and strings.

- act/tests/sample_files.py
- act/utils/io_utils.py
- tests/utils/test_io_utils.py
generate_movie() uses moviepy to convert a mpg to other format. If the mpg movie does not have duration parameter set moviepy will guess incorrectly and the converted movie is too short. Adding code to loop through mpg movie to get correct duration for conversion.
> Correctly set movie duration for conversion

- act/plotting/timeseriesdisplay.py
- examples/io/plot_sodar.py
- examples/plotting/plot_ceil.py
- examples/plotting/plot_time_height_scatter.py
- examples/qc/plot_qc_bsrn.py
- examples/templates/notebook_and_blog_template.ipynb
- tests/plotting/test_timeseriesdisplay.py
This is so that the code matches the correct terminology.
> ENH: Update the cb_friendly to match cvd_friendly.

- docs/source/userguide/usage.rst
As described above, also fixes a syntax issue further up in the document were hyperlink wasn't generating correctly.
> DOC: Update docs to explain how to get an arm username and token.

- act/utils/io_utils.py
There is an issue guessing the duration of the MPG movie when converting to another file type. If the time step of the movie is more than 0.1 then there can be multiple images that are the same. Checking multiple images being the same is how to determine the end of the movie. This fix allows some fudge factor by checking for multiple repeating images to signify the end.
> Getting correct length of MPG movie.

- act/io/__init__.py
> FIX: Wrong function name, causing ameriflux docs to not build.

- act/io/arm.py
- act/qc/arm.py
- act/qc/clean.py
- act/qc/qc_summary.py
- act/qc/qcfilter.py
- tests/discovery/test_asos.py
- tests/io/test_ameriflux.py
- tests/plotting/test_distributiondisplay.py
- tests/plotting/test_skewtdisplay.py
- tests/plotting/test_timeseriesdisplay.py
- tests/plotting/test_windrosedisplay.py
- tests/plotting/test_xsectiondisplay.py
- tests/qc/test_qc_summary.py
- tests/qc/test_qcfilter.py
These are some incremental updates to the method that creates a QC Summary. Also, working on improving the output netCDF file by improving how we correct the Dataset when writing to follow CF. Added some pytest.warn() to capture warnings and ensure they occur in our testing.
- [X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming
> Updates to making QC Summary files

- act/discovery/__init__.py
- act/discovery/nasa.py
- examples/discovery/download_mplnet.py
- tests/discovery/test_nasa.py
Notes: 
- MPLNET NETCDF4 files (at least Level 1) have some CFWarnings and fail our `read_arm_netcdf` I/O module. This is primarily due to the altitude dimension not containing a corresponding 1D coordinate within the files. 
- Will work on I/O function to correct these CFWarnings within the download files in a followup PR. 
- Module was named `nasa.py` as I anticipate eventually including discovery modules for NASA AERONET and PANDORA APIs as well.
> ADD: MPLNET Discovery Module

- act/qc/qctests.py
- tests/qc/test_qctests.py
This PR updates the persistence test to have a new keyword to allow ignoring the results of the test when the data values fall within a range of values. There are known times when values will fail the persistence test but there is not issue. e.g. weather station during a rain event has RH at 100%.
- [X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming
> Persistence test ignore range

- act/qc/bsrn_tests.py
- act/retrievals/radiation.py
- examples/qc/plot_qc_bsrn.py
- tests/qc/test_bsrn_tests.py
- tests/retrievals/test_radiation.py
This PR adds additional quality control tests for radiation data. Uses the Best Practices Handbook for the Collection and Use of Solar Resource Data for Solar Energy Applications: Fourth Edition. 
> Adding radiation quality control tests

- tests/discovery/test_airnow.py
Looks like the airnow tests are failing
> ENH: Fixing airnow tests

- README.rst
- docs/source/index.rst
The CI will most likely fail, seems to be an airnow comparison failing. Will need to check what changed in the airnow dataset. Removed the version 2.0 doc as well as its been quite some time.
> DOC: Add third roadmap info with survey link.

- act/io/arm.py
> FIX: `read_arm_mmcr` fails when using a read-only input file

- .github/workflows/ci.yml
Removing Python 3.9 as we want to check the 3 most recent versions.
> CI: Remove Python 3.9

- tests/qc/test_bsrn_tests.py
Something changed and the quality control tests were not being tripped. I've updated the testing data to trip the quality control tests.
- [ X ] PEP8 Standards or use of linter
- [ X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming
> Changed number of testing data to set off the tests.

- tests/qc/test_qcfilter.py
- tests/retrievals/test_sonde.py
The underlying library had a change to fix an issue. This changed the result of the test. Updated expected values for the test.
- [X ] Closes #910
> Scikit posthocs

- CONTRIBUTING.rst
1. Fix broken numpy link to acronyms on the contributor's guide
2. Fix wrong reference to `pyart` instead of `act`
> Fix a broken link and wrong text on the contributor's guide

- act/plotting/distributiondisplay.py
- tests/plotting/test_distributiondisplay.py
vert is deprecated, need to use orientation now.
> FIX: Update violin plot to use new parameter orientation.

- act/utils/io_utils.py
Removing duration calculation for mpg movies calculation. moviepy 2.* appears to have fixed this. Added duration keyword for movie generation to allow setting in case moviepy gets it wrong. Added additional check for moviepy version since that is now required for duration setting.
> Removing duration for mpg movies calculation.

- act/utils/io_utils.py
Updating the tar function so that it follows the changes stated for python 3.14. See docs here:
https://docs.python.org/3/library/tarfile.html#tarfile.TarFile.extractall
@AdamTheisen @mgrover1 If you both could review and see if this is fine. 'data' according to the docs looks to be the safest.
> FIX: Update extract function to new standards.

- act/discovery/arm.py
> ENH: adding error messages to discovery module

- tests/utils/test_io_utils.py
> FIX: Update posixpath generator to work in python 3.13.

- act/io/arm.py
- act/utils/data_utils.py
Xarray.open_dataset() is changing the default to keyword decode_timedelta to no longer default to None. This is raising a warning. This update checks the other keyword decode_times and sets decode_timedelta to the same value to keep the same functionality into the future.
- [X ] Closes #909 
> Setting decode_timedelta keyword in Xarray.open_dataset()
