ARM-DOE/ACT

- _mac/keymap.xml
- _mac/laf.xml
- act/plotting/plot.py
- act/utils/datetime_utils.py
- codestyles/Default.xml
- debugger.xml
- editor.codeinsight.xml
- filetypes.xml
- other.xml
- project.default.xml
- updates.xml
- vim_settings.xml
Dates passed to dates_between should be (start,end).  Current method was passing (end,start).
> BUG: day_night_background dates passed incorrectly to dates_between

- act/plotting/plot.py
@AdamTheisen was having issues with overlaying data onto pcolormesh plots. Being able to specify the line color would solve this issue.
> ADD: Can now specify plot color.

- act/plotting/plot.py
- act/utils/datetime_utils.py
Merging objects causing some issues with the attributes. Created some catches to help this
> ENH: Updating code to work off a merged object

- act/plotting/plot.py
- docs/source/installation.rst
The documentation instructions now refer to the right repository.
> DOC: Installation points to right repo

- act/io/armfiles.py
My second attempt at updating process to read files and return None if no files found.
> Updated to return None when requested if no files found

- act/plotting/plot.py
Adding option to limit yrange when there are values outside a reasonable range. Also fixed issue with yrng and multiple plots over a different range.
> Adding option to limit yrange when there are values outside a range

- act/plotting/__init__.py
- act/plotting/plot.py
- act/tests/test_plotting.py
Adding geographic plot for issue #45 .
> Geographic plot

- _sources/index.rst.txt
This should be the final file, just a different branch.
> DOC: Atmospheric spelled wrong.

- act/io/csvfiles.py
- act/plotting/plot.py
CSV reader engine was causing an issue when reading in NULL.
Removed a number of unused imports from the plot.py script
> ENH: Updates to the CSV reader to remove some hard coded options and removal of unused imports

- act/__init__.py
- act/io/__init__.py
- act/plotting/SkewTDisplay.py
- act/retrievals/__init__.py
- act/retrievals/stability_indices.py
- act/tests/test_retrieve_stability.py
- continuous_integration/environment-3.6.yml
- continuous_integration/environment-3.7.yml
- examples/plot_get_stability_indicies.py
- examples/plot_rh_timeseries.py
- examples/plot_skewt.py
ACT finally has a retrieval in it! Now we can compute CAPE, CIN, LCL, LFC, and lifted index from a sounding. This addresses #55.
> First retrieval in ACT: Compute CAPE, CIN, LCL, LFC, and lifted index from sounding.

- act/plotting/TimeSeriesDisplay.py
This fixes an error when trying to plot barb time series from two dimensional u, v fields.
> ADD: Small fix to TimeSeriesDisplay

- act/qc/qcfilter.py
- act/qc/qctests.py
- act/tests/test_qc.py
- act/utils/__init__.py
- act/utils/data_utils.py
- environment.yml
- examples/qc_example.py
- requirements.txt
Adding a difference test for time series data.  Also adding a function to convert units on data arrays wrapped around pint.
> Adding a difference test for time series data. 

- act/qc/__init__.py
- act/qc/qcfilter.py
- act/qc/qctests.py
I have taken Adam's updates and fixed a few issues to get the QC documentation to work.
> Updated to fix documentation

- MANIFEST.in
The new plotting txt file was left out.
> Additional MANIFEST Inclusions

- act/qc/qctests.py
Fixing some issues with persistence test and instrument comparison tests. Also now allowing None to be set for limits to indicate test should not be run. Something the DQ Office sets up in a loop.
> Test update

- act/tests/test_utils.py
- act/utils/__init__.py
- act/utils/geo_utils.py
Adding a function to utils area to calculate the destination lat/lon given a starting lat/lon and azimuth/distance.  There are libraries out there that do this, but was hesitant to add dependencies and given the simple nature thought it would be a good addition.
> Addition of geo_utils

- act/corrections/ceil.py
- act/corrections/doppler_lidar.py
- act/corrections/mpl.py
- act/corrections/raman_lidar.py
- act/corrections/ship.py
- act/discovery/get_CropScape.py
- act/discovery/get_armfiles.py
- act/io/armfiles.py
- act/io/clean.py
- act/io/csvfiles.py
- act/io/dataset.py
- act/plotting/ContourDisplay.py
- act/plotting/GeoDisplay.py
- act/plotting/SkewTDisplay.py
- act/plotting/TimeSeriesDisplay.py
- act/plotting/WindRoseDisplay.py
- act/plotting/XSectionDisplay.py
- act/plotting/common.py
- act/plotting/plot.py
- act/qc/qcfilter.py
- act/qc/qctests.py
- act/retrievals/__init__.py
- act/retrievals/cbh.py
- act/retrievals/doppler_lidar.py
- act/retrievals/pwv_calc.py
- act/retrievals/stability_indices.py
- act/utils/data_utils.py
- act/utils/datetime_utils.py
- act/utils/geo_utils.py
- act/utils/ship_utils.py
Fixing the documentation of the parameters and returns for almost all programs.  Changed the ' : ' to ': ' between the variable name and the type.  Also updating the documentation for the wind retrieval algorithm from DL PPIs to properly credit where the code came from.  Finally, updated the wind ship corrections to include proper reference to NOAA document.
> ENH: Documentation Improvement

- act/qc/qcfilter.py
Updated to use dask arrays in xarray object when creating a new QC field.
> Updated to use dask arrays in xarray object when creating a new QC field

- docs/source/CONTRIBUTING.rst
- examples/correct_ship_wind_data.py
@cgodine found a broken link in the Contributing documentation and there was a bug in one of the examples that has been fixed.
> Documentation and Example Fixes

- act/discovery/get_CropScape.py
- act/qc/__init__.py
- act/qc/arm.py
- act/tests/__init__.py
- act/tests/sample_files.py
- act/tests/test_CropScape.py
- act/tests/test_qc.py
Adding new function/program for working with ARM DQRs.  Also adding update for cropscape when the server is not functioning
> ARM DQR Capability 

- docs/source/index.rst
Adding example images, hid the api doc tree and adding basic introduction information. Also added links to conda and github downloads.
> DOC: Overhaul of index page.

- act/corrections/mpl.py
- act/tests/test_correct.py
Updates to fix issues with reading data that is 1D in multiple files and returning as 2D. Also updated some processing to use broadcasting.
There is an issue with the updated reading routine where variables in the file as 1D are made 2D because of a change between files. Xarray is now doing this because of the keyword change we made. Also, updated a few attributes in the returned object.
Made variable names keywords to allow updates outside of changing code.
> MPL Correction

- act/plotting/SkewTDisplay.py
Fixing issue with calculating u and v wind speeds from wind speed and wind direction. Also updated to allow nans in Temperature.
> skewt plot issue

- act/plotting/TimeSeriesDisplay.py
Error catching in day/night background if a valid lat/lon is not included in the file
> Error catching in day/night plotting

- act/tests/test_utils.py
- act/utils/__init__.py
- act/utils/datetime_utils.py
This adds a conversion to python datetime from numpy datetime64 to the datetime_utils.py module. A test is also added to the test_utils.py module.
> ADD: Adding datetime conversion to datetime_utils.py

- README.rst
- act/utils/data_utils.py
Subject says it all.  Found some typos and missing documentation.  Also added a small feature in the accumulate precip function.
> Documentation updates and enhancements to precip accumulation util

- act/discovery/__init__.py
- act/discovery/get_asos.py
- act/plotting/plot.py
- act/tests/test_asos.py
- examples/plot_asos_temp.py
- requirements.txt
I have added the ability to import ASOS data using the Iowa Mesonet Archive into an xarray dataset. Now we can specify regions or stations to download and get the data with ease.
> ADD: Ability to import Iowa Mesonet ASOS observations into xarray objects.

- act/qc/arm.py
Found a slight issue with the code at times when a qc variable was already in the obj.  This will check if a qc variable exists, if not, then add it.
> ENH: ARM DQR Webservice Function

- act/plotting/TimeSeriesDisplay.py
Finishing up issue #37 with location values and day night background plotting. This fix will handle vectors that contain nans. Also changed from throwing an error to showing a warning and returning without adding day/night background.
> Fixing day_night_background when some values in vector are nan.

- act/qc/qctests.py
Updated to have better default description for test when the two variables to be compared are in the same xarray dataset.
> Updated to have better default description for comparison test 

- act/qc/__init__.py
- act/qc/qctests.py
- act/retrievals/aeri.py
- act/tests/test_qc.py
Updated other code to be more better including ensure the attributes set for limits are correct type. Added more tests to test_qc.py to ensure attributes are correctly set. I think I fixed a possible issue with missing value test and higher dimention data.
> Adding delta test to QC

- act/qc/qcfilter.py
- act/qc/qctests.py
There is a strange issue getting indexes for setting tests from masked arrays. Switched to using numpy to get indexes and updated to allow boolean arrays in addition to index arrays for setting/adding tests. Should be a bit faster too.
> QC indexing

- README.rst
- setup.py
Working to fix the latest pypi problems.  This showed up in a check I did.
> BUG: Bug fix for release

- act/plotting/GeoDisplay.py
Added some additional logic to handle different projection requests. Does not add labels to plot but according to error that is not an option for all projections. Should resolve #160 .
> Fixing issue with adding gridlines on some projections.

- README.rst
- examples/multidata_example.py
Fixing an issue @scollis noted with one of the examples being unclear.  Also updating the README file to include the coveralls badge now that it is working and revamped the intro to include a reference to ARM and point towards the roadmap.
> Updates to examples and README

- act/plotting/TimeSeriesDisplay.py
- act/qc/radiometer_tests.py
- continuous_integration/environment-3.6.yml
- continuous_integration/environment-3.7.yml
- requirements.txt
Updating instances of astral to be compatible with the newest version of the library. Fix for #227
> Updating to use astral 2.2

- act/tests/test_utils.py
- act/utils/__init__.py
- act/utils/geo_utils.py
- examples/plot_daytime_averages.py
New feature to help with the calculation of daytime/nighttime periods for given locations.  Test and example have been included.  Tested across multiple locations but I'm sure there's something that may give problems in the future.
> ADD: Function for calculating daytime/nighttime/dawn/dusk

- act/plotting/WindRoseDisplay.py
Adding 3 features for legend formatting to the wind rose plotting code
> ENH: Adding new features to Wind Rose plotting

- act/plotting/TimeSeriesDisplay.py
- act/qc/qcfilter.py
- act/qc/radiometer_tests.py
- act/tests/test_qc.py
- act/tests/test_utils.py
- act/utils/geo_utils.py
- continuous_integration/environment-3.6.yml
- continuous_integration/environment-3.7.yml
- environment.yml
- requirements.txt
Conda only has astral 1.9.2 which is causing conflicts with the build and requirements for astral 2.2.  This update should handle both versions.
> Update to handle different astral versions

- act/io/__init__.py
- act/io/armfiles.py
- act/io/csvfiles.py
- act/io/mpl.py
- act/tests/test_io.py
Will want @rcjackson and @kenkehoe to take a look and see if this is appropriate or not.
> Altering OK and NO_DATASTREAM keywords with standards flag

- act/qc/qcfilter.py
- act/tests/test_qc.py
Implementing the request under issue #72 . This will read the embedded QC variables and apply the results to the data in the xarray dataset. Has options to allow user to fix possible issues if they arise. Default is to set data to numpy masked array.
> Data filter

- act/qc/qcfilter.py
- act/tests/test_qc.py
Found some issues when using flag values instead of flag masks.
> Setting tests with flag values instead of flag masks

- act/corrections/mpl.py
- act/tests/test_correct.py
Noticed an issue with the depol calc compared to what the mentor provided.  Updating that correction and the tests.
> Update to MPL Depol Ratio Calc

- act/corrections/mpl.py
- act/utils/data_utils.py
Updates to pyart conversion script for working with scanning data.
> PyART Script Updates

- act/qc/radiometer_tests.py
The updated to FFT test messed with the 'time' coordinate attributes. Bug fix to make sure the attributes are not removed.
> Radiometer tests

- act/utils/ship_utils.py
> BUG: Trying one fix at a time

- act/qc/radiometer_tests.py
Getting a RuntimeWarning when searching freq. Capturing the warning.
> Wrapping an index search to capture RuntimeWarning.

- act/tests/__init__.py
- act/tests/test_utils.py
My other unit test updates were not working.  Trying a new branch for testing.
> ENH: Testing unit tests additions for utils

- act/tests/test_correct.py
- act/tests/test_plotting.py
- act/tests/test_retrievals.py
- act/tests/test_utils.py
Will do other tests in other PR to avoid overwhelming.
> TST: Added tests and assert to raise coverage. Main focus stability indices in this PR.

- act/plotting/ContourDisplay.py
- act/tests/test_plotting.py
@AdamTheisen This is what I mentioned before with a parameter for contour, not sure if this is this route to go, however.
> TST: Addition of contour tests

- act/plotting/ContourDisplay.py
Cannot select a time when lat/lon are scalar and not the same size as the variable array.  This is a check for that
> Adding checks for contour plotting lat/lon

- CREATING_ENVIRONMENTS.rst
- README.rst
- act/qc/radiometer_tests.py
- act/tests/test_utils.py
- act/utils/geo_utils.py
- continuous_integration/environment-3.6.yml
- continuous_integration/environment-3.7.yml
- environment.yml
- requirements.txt
Updating add_solar_variable to use skyfield.  Also removing the references and dependency.  As part of this, the unit tests needed to be updated.
> Removing Astral Dependency Phase 2

- act/io/armfiles.py
- act/qc/clean.py
- act/tests/test_io.py
- act/tests/test_qc.py
- act/utils/geo_utils.py
Making some updates to the netCDF writer to add some additional attributes needed to write a CF compliant data file. This works with issue #252 . I've added attributes for the things I know about, but I would assume I missed one or two. Also, discovered an issue with the QC cleaner that I have updated.
> CF compliant

- docs/source/index.rst
Updates to the documentation index file to mimc the new Github Page view
> DOC: Updates to documentation

- MANIFEST.in
- act/tests/test_io.py
- setup.py
Build did not include csv files in the test area
> Conda errors

- act/io/armfiles.py
This should fix the error coming up in the conda PR
> BUG: Bug fix for conda release

- act/io/armfiles.py
- act/tests/test_plotting.py
There was a new bug introduced in updates for 0.7.0 that only manifested in the conda release.  This should hopefully fix that.
> ENH: Bug fixes for conda release

- act/qc/__init__.py
- act/qc/qcfilter.py
Also some mispells and docstring cleanup.
> DOC: Fix for datafilter missing from __init__.py

- README.rst
Testing out the travis build to make sure it's not an issue with the PR being open while migrating.
> ENH: Updating readme

- act/plotting/skewtdisplay.py
- act/plotting/timeseriesdisplay.py
- act/qc/arm.py
- act/tests/test_plotting.py
This is to fix issue #323 . Turns out it was adding a new test for each time range.
While testing found issue overplotting failing data and using absolute limits.
Since I was in there, decided to reduce warnings by using finally: with plot tests to close plot after used and capture warning with calculation of u & v direction.
> Fixing issues when adding DQRs to ACT object

- act/tests/test_qc.py
- act/tests/test_utils.py
- act/utils/data_utils.py
I noticed add_in_nan() taking a long time to work. After looking into it I think we were adding too many NaN values for what was needed. The updates will only add in one or one row of NaNs using the build in numpy functions which is much faster. Also, changed to return the data in same type Number or Xarray.DataArray as supplied to the function.
> Add in nan

- act/discovery/get_airnow.py
Added function to pull the AirNow data from the AirNow API. Two of the functions just pull the data and display them on screen and the last one will download a file. Working on adding the option to download files with the other functions that just print to the screen. 
Need to figure out how to unit test since a users private token is needed to access the data.
> ADD: get_airnow functionality

- act/discovery/get_airnow.py
> Revert "Revert "ADD: get_airnow functionality""

- act/qc/qcfilter.py
The ValueError message indicates the wrong function. This just fixes the printed message.
> Fixing message with ValueError

- act/discovery/get_cropscape.py
- act/io/noaapsl.py
- act/plotting/geodisplay.py
- act/tests/test_io.py
Fixes most warnings caused by act code itself, other warnings from dependencies themselves aren't fixed here. 
Uses new syntax for pyproj to remove dep warning. Using no labels to remove cartopy dep. Fixes regex warning.
> FIX: Fixes most warnings within ACT.

- .travis.yml
- continuous_integration/environment-3.9.yml
Adding python 3.9 environment. Dependencies should be stable now. Removing doc build for 3.7.
> CI: Adding 3.9 testing environment.

- act/qc/sp2.py
Fixing the cal_file_name issue in qc/sp2.py.
> cal_file_name fix

- act/qc/qcfilter.py
- act/tests/test_qc.py
> Fixing bitwise comparisons with QC data

- .github/workflows/build-docs.yml
I noticed the docs did not start to build since I used main instead of master
> Update branch to master not main

- docs/source/conf.py
Update to use the new google analytics ID that won't be replaced in a year
> Add new google analytics ID

- docs/source/conf.py
After checking the dashboard, it looks like the analytics aren't working.. this fixes that bug
> Fix Google Analytics ID bug

- continuous_integration/environment_actions.yml
Added PySP2 to development environment for coveralls.
> ADD: PySP2 to development environment

- act/plotting/skewtdisplay.py
Tested this on the problem files noted in #372 and looks to work.  Will want @kenkehoe and @ajsockol to take a look as well.
> ENH: Fix for when pressure values are the same or decrease

- docs/source/blog.md
Currently, we are missing the blog page. This adds in the blank page that will allow the docs to build it.
> Add blog page

- act/io/noaagml.py
- act/tests/test_io.py
The SPASH campaign in Crested Butte, CO has changed those files for Radiation data. This update fixed the number of columns expected for that campaign. Also fixed issue where kwargs were not being passed into pandas.read_csv().
Also, discovered an issue reading the data file. The first line was not being read. This should resolve those issues.
> NOAA GML data

- act/discovery/get_armfiles.py
- act/tests/test_utils.py
- act/utils/__init__.py
- act/utils/datetime_utils.py
@AdamTheisen Is this kinda what you had in mind for #448 ? Any of these formats are accepted and then turned into the proper string for the query. If so I can add unittests as well.
> ENH: Adding date parser to get_armfiles.

- act/io/armfiles.py
Also fixed an issue with using pathlib.Path().
> Added keyword to apply clean.cleanup() method instead of requiring the method call after reading data.

- act/qc/__init__.py
- act/qc/bsrn_tests.py
- act/qc/clean.py
- act/qc/qcfilter.py
- act/retrievals/radiation.py
- act/tests/test_io.py
- act/tests/test_qc.py
- act/tests/test_retrievals.py
- act/tests/test_utils.py
- act/utils/geo_utils.py
- examples/plot_qc_bsrn.py
The BSRN group have a set of standard tests they use for evaluating data. The tests were written by Chuck Long and Ellsworth Dutton, both long time ARM people. These tests should work well with ARM and any other radiation data sets.
> Adding BSRN QC tests

- act/io/armfiles.py
- act/qc/clean.py
- act/qc/qcfilter.py
- act/qc/qctests.py
- act/tests/test_io.py
- act/tests/test_qc.py
Updated documentation within the methods and function calls.
Added a new test to use MetPy pressure derived from altitude
to check if values are within expected range.
Fixed issue with writing to file in CF format and reading file
back into Dataset. There was an issue with the flag_* variable
attributes not being in a list or array as expected when only one
value exists.
Added additional tests for the new atmospheric pressure testing
function.
I tried to keep the updates in this separate from PR #465 but I may have some of those as well. Does it matter?
> Improved documentation and new atmospheric pressure test.

- act/qc/arm.py
- act/qc/qcfilter.py
- act/tests/test_qc.py
I noticed that the documentation in QC area was not consistent and lacking in examples. I've updated much of the documentation.
Discovered a better way to parse the bits using numpy so implemented that. Left old code for now for reference.
Discovered a keyword for applying DQRs was not actually used. It is not needed. Took it out.
No rush to integrate this. I plan to do other PRs for documentation updates to make the process more manageable.
> Documentation update

- act/discovery/get_cropscape.py
- act/qc/add_supplemental_qc.py
- act/qc/arm.py
- act/qc/clean.py
- act/qc/qctests.py
- docs/environment_docs.yml
Backwards compatibility for pyproj to help with ADC systems.
> FIX: Backwards compatability for pyproj for python<3.8.

- act/io/armfiles.py
- examples/plot_qc_bsrn.py
IO combine_attrs passed to open_mfdataset when there's only 1 file
> IO combine_attrs bug

- act/tests/test_discovery.py
> ENH: Updates for airnow

- .github/workflows/python-package-conda.yml
- act/plotting/timeseriesdisplay.py
- act/tests/test_plotting.py
- act/tests/test_qc.py
Note, this is for testing purposes only, do not merge at this time.
> ENH: Updating to test on 3.6 and 3.7 again for test purposes

- act/discovery/get_armfiles.py
- act/tests/test_discovery.py
- act/utils/datetime_utils.py
> ENH: Support searching at the second level for ARM data

- act/discovery/get_armfiles.py
- act/io/noaapsl.py
- act/tests/test_utils.py
> FIX: Add more robust parsing method to PSL Temperature data

- act/discovery/get_armfiles.py
It looks like it was passing the datetime string instead of the datetime object... this fixes that
> FIX: Pass datetime to function not str

- act/discovery/get_armfiles.py
Fix behavior of ARM data search when start date == end date
Closes #499
> FIX: Add check for same datetime

- act/tests/test_plotting.py
- continuous_integration/environment_actions.yml
- docs/environment_docs.yml
- docs/source/API/index.rst
Closes #509 
This fixes our failing API reference guide links and such
> FIX: Update API reference to build links

- act/io/noaagml.py
Particularly carbon dioxide was suppose to be ozone for gml_ozone and meteorological was spelled wrong.
> DOC: Fix of typos and mispellings as well as PEP8 changes.

- examples/plot_airnow.py
Example is not working correctly
> ENH: Updating example to try and get it to run

- act/io/noaapsl.py
Remove the hard coded site identifier, making it more generic to work with any site 
Closes #502
> Make noaa psl wind profiler more generic

- examples/plot_icartt.py
Title correction to the ICARTT plotting example.
> BUG: Correction to title of the ICARTT example

- act/discovery/get_armfiles.py
Closes #532 , @AdamTheisen This now checks for that message and then either raises a download error or continues on and downloads the files. I'm not sure if this is the most robust way.
> MNT: Update to check for a level files etc.

- act/discovery/get_armfiles.py
> Revert "MNT: Update to check for a level files etc."

- act/__init__.py
- act/qc/__init__.py
Closes #552 
@AdamTheisen accessors need to eagerly loaded in... there is not a performance decrease to doing this which is nice. This fixes the issue.
> FIX: Fix issues with lazy loading accessors

- examples/plot_examples.py
This plot example shows how to resample data, plot using xarray, and access the axes in the display object for more customization
> ENH: Adding plot example to resolve #460 and #57

- act/__init__.py
- act/corrections/__init__.py
- act/discovery/get_noaapsl.py
- act/plotting/timeseriesdisplay.py
- act/qc/__init__.py
- act/qc/qctests.py
- act/tests/__init__.py
- act/utils/__init__.py
- examples/README.rst
- examples/plot_icartt.py
We were missing some of the functions in the __init__.py files.  We might want to do an inventory to make sure we aren't missing anything else.
> Adding functions to the __init__.py files

- act/retrievals/doppler_lidar.py
- act/tests/test_retrievals.py
There was a bug in the code that set the snr_name when there were processes dependent on the snr_name.  So when multiple datasets were in an object, the first one ran correctly but the rest did not.  This should resolve that.  I also upgraded it to use dask processing to speed it up.  One day took about 4 seconds to process which was a significant improvement from before which took 10+ seconds.
> Bug fix for the compute_winds_from_ppi code

- act/tests/test_io.py
- examples/plotting/plot_skewt_with_text.py
Closes #606 
Shows how to add text to the skewt display
> ADD: Add an example plotting text on a skewt

- act/plotting/timeseriesdisplay.py
- examples/discovery/plot_neon.py
- examples/plotting/plot_ceil.py
- examples/qc/plot_qc_bsrn.py
This would close out #604  but introduces a keyword for the timeseries plot and the qc plot to use colorblind friendly colors.  RGB values were taken from the HomeyerRainbow cmap.
> Cb friendly

- .github/workflows/python-package-conda.yml
- README.rst
- codecov.yml
Coveralls is going to a pay model. Switch from coveralls to codecov.
> CI: Switching to codecov

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds codeowners file and an basic issue and pull request template.
> ADD: Adding codeowners, issue template and pull template.

- act/utils/inst_utils.py
> Present weather decoder updates for robustness

- act/utils/inst_utils.py
- examples/io/plot_create_arm_ds.py
I think this would suffice for taking care of #591 .  I think it is easy enough to update/add attributes using xarray that ACT does not need the added functionality to set these specific attributes for the users.
> Dod example

- act/discovery/__init__.py
- act/discovery/get_armfiles.py
- act/tests/test_discovery.py
> Doi Bug Fix

- act/utils/inst_utils.py
> MNT: Add supplement table when codes are not present in 4680.

- act/discovery/get_armfiles.py
- act/tests/test_discovery.py
> Doi update

- .github/workflows/build-docs.yml
- .github/workflows/python-package-conda.yml
This migrates to the new github action for building the docs
> FIX: Fix the github action for building docs

- examples/workflows/plot_aerioe_with_cbh.py
> Add AERIoe workflow example

- act/plotting/distributiondisplay.py
- act/tests/test_plotting.py
- examples/plotting/plot_heatmap.py
- examples/plotting/plot_scatter.py
- examples/plotting/plot_violin.py
* Updated DistributionDisplay Violin and Scatter plots to use ACT conventions (i.e. plot_violin; plot_scatter)
* Updated testing files to use this naming convention
* Updated example files for this naming convention
* Updated Scatter plot example to calculate best fit line and pearson correlation coefficient
> ENH: updated DistributionDisplay Scatter/Violin names, examples

- README.rst
> DOC: Update readme to reflect dependencies.

- act/plotting/skewtdisplay.py
I used the GitHub editor so we will see how this works!
> Update skewtdisplay.py documentation

- .github/workflows/build-docs.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/python-package-conda.yml
Upgrades various actions and makes sure the proper variables are set for the micromamba action
> FIX: Upgrade various actions and ensure proper env name is set

- .coveragerc
Ensure submodules are added to the coverage configuration file.
> CI: Update coveragerc.

- .coveragerc
- codecov.yml
We missed one script in the code coverage
> ENH: Adding airnow to codecov

- act/tests/test_utils.py
- act/utils/__init__.py
- act/utils/data_utils.py
> ADD: Adding arm site and facility location coordinate elastic search.

- act/utils/data_utils.py
Won't close the issue until it's confirmed on the user end that this in fact fixes the issue. Seems to fix the issue locally.
> FIX: Fix for arm_elastic_search, missing space causing search issues.

- README.rst
> DOC: Update readme for version 2.0.

- docs/environment_docs.yml
Pin specific versions of sphinx to fix the doc build issues
> FIX: Fix the sphinx doc build issue

- docs/environment_docs.yml
- docs/source/conf.py
Fix the sphinx build with gallery
> FIX: Fix example gallery build

- README.rst
> DOC: Update README for version 2.0

- .github/dependabot.yml
Add dependabot to check for changes in github action dependencies etc.
> CI: Add dependabot.yml

- .github/workflows/ci.yml
> ADD: Add nightly build in CI

- docs/source/blog_posts/2024/2024_Eclipse_SGP.ipynb
> ENH: Metadata changes for blog posts

- act/plotting/geodisplay.py
> DOC: Update geoplot missing return doc.

- act/plotting/timeseriesdisplay.py
Just a removal of a left over print statement.
> Removing a debug print statement.

- act/qc/__init__.py
> FIX: Fixes missing docs for clean.py module.

- act/plotting/timeseriesdisplay.py
> ENH: Adding keywords to plot_barbs_from_u_v to better plot up the barbs

- act/discovery/__init__.py
- act/discovery/airnow.py
- act/discovery/improve.py
- examples/discovery/plot_improve.py
- tests/discovery/test_improve.py
> Adding IMPROVE discovery module

- act/discovery/arm.py
- act/discovery/asos.py
- act/io/conf/noaapsl_SurfaceMet.yaml
- examples/discovery/plot_asos_temp.py
- examples/workflows/plot_amf3_comparisons.py
- tests/discovery/test_asos.py
> ADD: Adding example for bringing BNF data sources together for plotting

- act/qc/qctests.py
- examples/qc/plot_qc_step_change.py
- tests/qc/test_qctests.py
This is adding a new test to check for shift in data values. I have also included an example in the examples directory with a plot.
- [X ] Xarray Dataset or DataArray variable naming follows 'ds' or 'da' naming
> Adding step detection test

- docs/source/conf.py
> FIX: Fix the analytics ID

- README.rst
- docs/source/index.rst
- requirements-dev.txt
- requirements.txt
> ENH: Add docs for arm-test-data and add to requirements.

- act/discovery/ameriflux.py
Remove os path join, not needed here
> FIX: os path join was adding windows path for url, which breaks.

- act/utils/data_utils.py
> Fix: Update request_type to POST for arm site location search with elastic search

- act/discovery/__init__.py
- act/discovery/arm.py
- tests/discovery/test_arm_discovery.py
> ENH: Add tool that uses arm discovery mod API and updates paths.

- README.rst
> DOC: Readme update.

- act/discovery/ameriflux.py
@AdamTheisen This should use the correct link now?
> DOC: Update broken link.
